# Task 3 - Lane Line Detection
Mageshwaran Sankar

In [11]:
import cv2
import numpy as np

video = cv2.VideoCapture("test videos/test3.mp4")

while True:
    ref, frame = video.read()
    hsv_full=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV_FULL)
    # hls_full=cv2.cvtColor(frame,cv2.COLOR_BGR2HLS_FULL)

    inner_1=np.array([17,67,171])
    outer_1=np.array([29,104,253])
    mask_lane=cv2.inRange(hsv_full,inner_1,outer_1)

    # inner_2=np.array([182,244,255])
    # outer_2=np.array([182,230,124])
    # mask_corners=cv2.inRange(hls_full,inner_2,outer_2)

    mask=mask_lane #+mask_corners
    edges=cv2.Canny(mask,0,150,apertureSize=7,L2gradient=True)

    lines=cv2.HoughLinesP(edges,1,np.pi/180,threshold=50,maxLineGap=200,minLineLength=50)
    
    if lines is not None:
        for line in lines:
            x1,y1,x2,y2=line[0]                                 
            cv2.line(frame,(x1,y1),(x2,y2),(255,0,255),1)
    
    # if not ret:
    #     video=cv2.VideoCapture("test videos/test1.mp4")
    #     continue
    cv2.imshow("Frame",frame)
    cv2.imshow("hsv",hsv_full)
    cv2.imshow("Mask",mask)
    cv2.imshow("Edges",edges)

    key=cv2.waitKey(1)
    if key == 27:           #press esc button to break the while loop
        break

video.release()
cv2.destroyAllWindows()

In [7]:
print(lines)

[[[ 99 693 523 374]]

 [[ 65 691 497 389]]

 [[ 63 696 514 380]]

 [[122 650 494 389]]

 [[146 685 526 377]]

 [[ 63 694 502 387]]

 [[145 684 525 376]]

 [[169 684 525 386]]

 [[171 684 525 387]]

 [[ 92 694 481 401]]

 [[ 94 694 436 436]]

 [[145 682 524 375]]

 [[ 96 694 513 380]]

 [[174 684 366 523]]

 [[172 681 525 385]]

 [[172 684 502 407]]

 [[145 681 515 381]]

 [[145 683 525 375]]

 [[ 91 694 495 389]]

 [[151 683 522 383]]

 [[167 684 525 384]]

 [[147 685 521 382]]

 [[156 651 505 388]]

 [[202 593 449 420]]

 [[ 63 695 522 374]]]
